---
abstract: 'File logger supports log rotation'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Test::MockTime: 0
  Test::More: 0
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.4, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-RotateLogs
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  File::RotateLogs:
    file: lib/File/RotateLogs.pm
    version: 0.05
requires:
  Mouse: 1.02
  Proc::Daemon: 0.14
resources:
  bugtracker: https://github.com/kazeburo/File-RotateLogs/issues
  homepage: https://github.com/kazeburo/File-RotateLogs
  repository: git://github.com/kazeburo/File-RotateLogs.git
version: 0.05
x_contributors:
  - 'SUZUKI Masashi <m15.suzuki.masashi@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
